project:
  type: book

book:
  title: "Trabalho Final de Regress√£o Linear"
  subtitle: "Maria Luiza B. Quirino (190113456), Poliana Matos (190115670) e Rafael de Acypreste (200060023)"
  author: "Professora Maria Theresa"
  date: "12/20/2023"
  chapters:
    - index.qmd
    - objetivos.qmd
    - metodologia.qmd
    - resultados.qmd
    - references.qmd

toc: true
number-sections: true
number-depth: 4
execute:
  warning: false
  echo: false
  eval: true
  message: false

bibliography: references.bib

format:
  PrettyPDF-pdf:
    keep-tex: true



